//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PulseLTD_Exercise.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class PhotoAlbum
    {
        public int ImageId { get; set; }
        public string ImageTitle { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageText { get; set; }
        public Nullable<System.DateTime> ImageDateTime { get; set; }
        //public HttpPostedFileBase ImageFile { get; set; }
    }
}
